### ISSUE TITLE
Download processed table doesn't work

### ISSUE THREAD

**Issue by manu-leo** [czbiohub/pyseus#29]
Here what i came across:
- at `pre_processing` stage `Data processing` tab
- tried to `download processed MS table` but forgot to put a name, so got an error
- now the  `download processed MS table` option doesn’t work even though I put a name
Not sure if related to my first error

Thanks!

**Comment by kkimatx** [comment]
Fixed. Unnamed files will automatically download as "unnamed_preprocessed_table.csv", and further downloads will still work.
